### ISSUE TITLE
Library doesn't work with Nette/di v3.0.0-RC2

### ISSUE THREAD

**Issue by chrfritsch** [mglaman/phpstan-drupal#47]
Since yesterday evening I got the following error on https://travis-ci.org/BurdaMagazinOrg/thunder-distribution/jobs/511585322:

```
PHP Fatal error:  Uncaught Nette\MemberAccessException: Call to undefined method Nette\DI\Definitions\ImportedDefinition::getFactory(). in /home/travis/build/BurdaMagazinOrg/test-dir/vendor/nette/utils/src/Utils/ObjectHelpers.php:65
Stack trace:
#0 /home/travis/build/BurdaMagazinOrg/test-dir/vendor/nette/utils/src/Utils/SmartObject.php(42): Nette\Utils\ObjectHelpers::strictCall('Nette\\DI\\Defini...', 'getFactory')
#1 /home/travis/build/BurdaMagazinOrg/test-dir/vendor/mglaman/phpstan-drupal/src/DependencyInjection/DrupalExtension.php(71): Nette\DI\Definitions\Definition->__call('getFactory', Array)
#2 /home/travis/build/BurdaMagazinOrg/test-dir/vendor/nette/di/src/DI/Compiler.php(233): PHPStan\DependencyInjection\DrupalExtension->loadConfiguration()
#3 /home/travis/build/BurdaMagazinOrg/test-dir/vendor/nette/di/src/DI/Compiler.php(185): Nette\DI\Compiler->processExtensions()
#4 /home/travis/build/BurdaMagazinOrg/test-dir/vendor/nette/di/src/DI/ContainerLoader.php(119): Nette\DI\Compiler->compile()
#5 /home/travis/build/BurdaMa in /home/travis/build/BurdaMagazinOrg/test-dir/vendor/nette/utils/src/Utils/ObjectHelpers.php on line 65
```

Looks like they changed something and broke the API

**Comment by chrfritsch** [comment]
There are also problems in https://github.com/phpstan/phpstan/issues/2033

**Comment by chrfritsch** [comment]
Here is a PR
https://github.com/mglaman/phpstan-drupal/pull/48
