### ISSUE TITLE
Uncaught error: Cannot unset string offsets - DrupalExtension.php:152

### ISSUE THREAD

**Issue by rasben** [mglaman/phpstan-drupal#477]
This is a duplicate of the issue here, but I dont have access to re-open it:

https://github.com/mglaman/phpstan-drupal/issues/79

```
PHP Fatal error:  Uncaught Error: Cannot unset string offsets in phar:///tmp/drupal-check/vendor/mglaman/phpstan-drupal/src/DependencyInjection/DrupalExtension.php:152
Stack trace:
#0 phar:///tmp/drupal-check/vendor/nette/di/src/DI/Compiler.php(232): PHPStan\DependencyInjection\DrupalExtension->loadConfiguration()
#1 phar:///tmp/drupal-check/vendor/nette/di/src/DI/Compiler.php([20](https://github.com/reload/storypal/actions/runs/3151245237/jobs/5147905382#step:5:21)7): Nette\DI\Compiler->processExtensions()
#2 phar:///tmp/drupal-check/vendor/nette/di/src/DI/ContainerLoader.php(119): Nette\DI\Compiler->compile()
#3 phar:///tmp/drupal-check/vendor/nette/di/src/DI/ContainerLoader.php(79): Nette\DI\ContainerLoader->generate()
#4 phar:///tmp/drupal-check/vendor/nette/di/src/DI/ContainerLoader.php(44): Nette\DI\ContainerLoader->loadFile()
#5 phar:///tmp/drupal-check/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(242): Nette\DI\ContainerLoader->load()
#6 phar:///tmp/drupal-check/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(2[21](https://github.com/reload/storypal/actions/runs/3151245237/jobs/5147905382#step:5:22)): Nette\Configurator->loadContainer()
#7 phar:///tmp/drupal-check/vendor/phpst in phar:///tmp/drupal-check/vendor/mglaman/phpstan-drupal/src/DependencyInjection/DrupalExtension.php on line 152
reviewdog: EOF

```

As @opdavies points out, it's an issue that this patch introduced: https://www.drupal.org/node/3021898

But, now that patch has been merged to Drupal core.

**Comment by mglaman** [comment]
I don't think this is valid anymore. The hacky dependency injection stuff was removed some time ago.

**Comment by mglaman** [comment]
Last comment was wrong, looked at previous issue and it appears to be this code? https://github.com/mglaman/phpstan-drupal/blob/main/src/Drupal/DrupalAutoloader.php#L158-L188

**Comment by mglaman** [comment]
Closing, seems to be fixed.
