### ISSUE TITLE
Rendering a lazy_builder element within a Filter plugin throwing error

### ISSUE THREAD

**Issue by pfrilling** [mglaman/phpstan-drupal#519]
I have a bit of an edge case here, but wanted to bubble it up.

I have a `#lazy_builder` render array that is being generated in a Filter plugin. The code is using a the `\Drupal\Core\Render\RendererInterface` service to render the lazy builder callback code within the processed text.

The relevant PHP code within the plugin looks like this:
```
  /**
   * {@inheritdoc}
   */
  public function process($text, $langcode): FilterProcessResult {
    $rendered_codes = [];
    $result = new FilterProcessResult();

    $processor = function (array $matches) use (&$rendered_codes, $result): string {
      // The code is stored as an escaped string, see CKEditor plugin.
      $code = htmlspecialchars_decode($matches[1]);

      if (!isset($rendered_codes[$code])) {
        $element = [
          '#lazy_builder' => [
            'my_module.lazy_builders:renderCallbackMethod',
            [
              $code,
            ],
          ],
          '#create_placeholder' => TRUE,
        ];
        $rendered_codes[$code] = $this->renderer->render($element);

        // Merge the bubbleable metadata into the result.
        $result->addCacheableDependency(
          BubbleableMetadata::createFromRenderArray($element)
        );
      }

      return (string) $rendered_codes[$code];
    };
    $processed_text = preg_replace_callback(
      '@\[MYMODULE\-PROMO\-CODE\:([^\]]+)\]@i',
      $processor,
      $text
    );
    $result->setProcessedText($processed_text);

    return $result;
  }
```

This is causing the following PHP error when running the upgrade status check on the code:

```
Uncaught Error: Call to undefined method PHPStan\Type\Constant\ConstantStringType::isClassStringType() in /app/vendor/mglaman/phpstan-drupal/src/Rules/Drupal/RenderCallbackRule.php:225
#0 /app/vendor/mglaman/phpstan-drupal/src/Rules/Drupal/RenderCallbackRule.php(134): mglaman\PHPStanDrupal\Rules\Drupal\RenderCallbackRule->getType(Object(PhpParser\Node\Scalar\String_), Object(PHPStan\Analyser\MutatingScope))
#1 /app/vendor/mglaman/phpstan-drupal/src/Rules/Drupal/RenderCallbackRule.php(101): mglaman\PHPStanDrupal\Rules\Drupal\RenderCallbackRule->doProcessNode(Object(PhpParser\Node\Scalar\String_), Object(PHPStan\Analyser\MutatingScope), '#lazy_builder', 0)
#2 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(106): mglaman\PHPStanDrupal\Rules\Drupal\RenderCallbackRule->processNode(Object(PhpParser\Node\Expr\ArrayItem), Object(PHPStan\Analyser\MutatingScope))
#3 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(98): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Expr\ArrayItem), Object(PHPStan\Analyser\MutatingScope))
#4 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(504): PHPStan\Node\ClassStatementsGatherer->__invoke(Object(PhpParser\Node\Expr\ArrayItem), Object(PHPStan\Analyser\MutatingScope))
#5 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2548): PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}(Object(PhpParser\Node\Expr\ArrayItem), Object(PHPStan\Analyser\MutatingScope))
#6 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2461): PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}(Object(PhpParser\Node\Expr\ArrayItem), Object(PHPStan\Analyser\MutatingScope))
#7 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1463): PHPStan\Analyser\NodeScopeResolver->callNodeCallbackWithExpression(Object(Closure), Object(PhpParser\Node\Expr\ArrayItem), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Analyser\ExpressionContext))
#8 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1896): PHPStan\Analyser\NodeScopeResolver->processExprNode(Object(PhpParser\Node\Expr\ArrayItem), Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\ExpressionContext))
#9 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1478): PHPStan\Analyser\NodeScopeResolver->processExprNode(Object(PhpParser\Node\Expr\Array_), Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\ExpressionContext))
#10 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2751): PHPStan\Analyser\NodeScopeResolver->PHPStan\Analyser\{closure}(Object(PHPStan\Analyser\MutatingScope))
#11 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1486): PHPStan\Analyser\NodeScopeResolver->processAssignVar(Object(PHPStan\Analyser\MutatingScope), Object(PhpParser\Node\Expr\Variable), Object(PhpParser\Node\Expr\Array_), Object(Closure), Object(PHPStan\Analyser\ExpressionContext), Object(Closure), true)
#12 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(556): PHPStan\Analyser\NodeScopeResolver->processExprNode(Object(PhpParser\Node\Expr\Assign), Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\ExpressionContext))
#13 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(358): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Expression), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#14 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(644): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\If_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#15 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(358): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\If_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#16 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2584): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Expr\Closure), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#17 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1844): PHPStan\Analyser\NodeScopeResolver->processClosureNode(Object(PhpParser\Node\Expr\Closure), Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\ExpressionContext), NULL)
#18 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1478): PHPStan\Analyser\NodeScopeResolver->processExprNode(Object(PhpParser\Node\Expr\Closure), Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\ExpressionContext))
#19 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2751): PHPStan\Analyser\NodeScopeResolver->PHPStan\Analyser\{closure}(Object(PHPStan\Analyser\MutatingScope))
#20 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1486): PHPStan\Analyser\NodeScopeResolver->processAssignVar(Object(PHPStan\Analyser\MutatingScope), Object(PhpParser\Node\Expr\Variable), Object(PhpParser\Node\Expr\Closure), Object(Closure), Object(PHPStan\Analyser\ExpressionContext), Object(Closure), true)
#21 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(556): PHPStan\Analyser\NodeScopeResolver->processExprNode(Object(PhpParser\Node\Expr\Assign), Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\ExpressionContext))
#22 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(358): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Expression), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#23 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(519): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#24 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(358): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#25 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(597): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#26 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(358): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#27 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(569): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#28 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(328): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#29 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(175): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#30 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(71): PHPStan\Analyser\FileAnalyser->analyseFile('/app/web/module...', Array, Object(PHPStan\Rules\LazyRegistry), Object(PHPStan\Collectors\Registry), NULL)
#31 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(63): PHPStan\Analyser\Analyser->analyse(Array, Object(Closure), NULL, true, Array)
#32 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(207): PHPStan\Command\AnalyserRunner->runAnalyser(Array, Array, Object(Closure), NULL, true, true, '/tmp/upgrade_st...', NULL, NULL, Object(_PHPStan_d91411b2a\Symfony\Component\Console\Input\ArgvInput))
#33 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(101): PHPStan\Command\AnalyseApplication->runAnalyser(Array, Array, true, '/tmp/upgrade_st...', Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), Object(_PHPStan_d91411b2a\Symfony\Component\Console\Input\ArgvInput))
#34 phar:///app/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(168): PHPStan\Command\AnalyseApplication->analyse(Array, false, Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), false, true, '/tmp/upgrade_st...', Array, Object(_PHPStan_d91411b2a\Symfony\Component\Console\Input\ArgvInput))
#35 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute(Object(_PHPStan_d91411b2a\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_d91411b2a\Symfony\Component\Console\Output\ConsoleOutput))
#36 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(868): _PHPStan_d91411b2a\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_d91411b2a\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_d91411b2a\Symfony\Component\Console\Output\ConsoleOutput))
#37 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(259): _PHPStan_d91411b2a\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_PHPStan_d91411b2a\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_d91411b2a\Symfony\Component\Console\Output\ConsoleOutput))
#38 phar:///app/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_d91411b2a\Symfony\Component\Console\Application->doRun(Object(_PHPStan_d91411b2a\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_d91411b2a\Symfony\Component\Console\Output\ConsoleOutput))
#39 phar:///app/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124): _PHPStan_d91411b2a\Symfony\Component\Console\Application->run()
#40 phar:///app/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125): _PHPStan_d91411b2a\{closure}()
#41 /app/vendor/phpstan/phpstan/phpstan(8): require('phar:///app/ven...')
#42 /app/vendor/bin/phpstan(120): include('/app/vendor/php...')
```

**Comment by pfrilling** [comment]
My `composer.lock` file was locking my version of `phpstan` to an old version, which is why I was seeing this error. Getting the packages on the latest version fixed the issue. :man_facepalming:
