### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by ragnarkurmwunder** [mglaman/phpstan-drupal#580]
# Bug report

## Versions

```
PHPStan - PHP Static Analysis Tool 1.10.21
```

```
"name": "mglaman/phpstan-drupal",
"version": "1.1.35",
```

# Code snippet that reproduces the problem

```php
<?php

class a {
  public function a() {
    function a() {
      \Drupal::a();
    }
  }
}
```

# Original reference

[PhpStan](https://github.com/phpstan/phpstan/issues/9520)

# The source of the problem

https://github.com/mglaman/phpstan-drupal/blob/7da46c12bd556dca5855ee76b8621815d85714fe/src/Rules/Drupal/GlobalDrupalDependencyInjectionRule.php#L63-L70

according to @ondrejmirtes.

# The command output

```txt
www-data@41b52d4f9d36:/app/drupal/web$ phpstan analyze --level=5 -v -- _ping.php
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100% 6 secs

 -- -----------------------------------------------------------------------------------------------------------------------------------------------------------------
     Error
 -- -----------------------------------------------------------------------------------------------------------------------------------------------------------------
     Internal error: Internal error: Internal error. in file /app/drupal/web/_ping.php

     Post the following stack trace to https://github.com/phpstan/phpstan/issues/new?template=Bug_report.yaml:
     #0 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(104):
     mglaman\PHPStanDrupal\Rules\Drupal\GlobalDrupalDependencyInjectionRule->processNode(Object(PhpParser\Node\Expr\StaticCall),
     Object(PHPStan\Analyser\MutatingScope))
     #1 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(98):
     PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Expr\StaticCall), Object(PHPStan\Analyser\MutatingScope))
     #2 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(524):
     PHPStan\Node\ClassStatementsGatherer->__invoke(Object(PhpParser\Node\Expr\StaticCall), Object(PHPStan\Analyser\MutatingScope))
     #3 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(462):
     PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}(Object(PhpParser\Node\Expr\StaticCall), Object(PHPStan\Analyser\MutatingScope))
     #4 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2602):
     PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}(Object(PhpParser\Node\Expr\StaticCall), Object(PHPStan\Analyser\MutatingScope))
     #5 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1548):
     PHPStan\Analyser\NodeScopeResolver->callNodeCallbackWithExpression(Object(Closure), Object(PhpParser\Node\Expr\StaticCall),
     Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Analyser\ExpressionContext))
     #6 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(1708):
     PHPStan\Analyser\NodeScopeResolver->processExprNode(Object(PhpParser\Node\Expr\StaticCall), Object(PHPStan\Analyser\MutatingScope), Object(Closure),
     Object(PHPStan\Analyser\ExpressionContext))
     #7 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(557):
     PHPStan\Analyser\NodeScopeResolver->processExprNode(Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\MutatingScope), Object(Closure),
     Object(PHPStan\Analyser\ExpressionContext))
     #8 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(371):
     PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Return_), Object(PHPStan\Analyser\MutatingScope), Object(Closure),
     Object(PHPStan\Analyser\StatementContext))
     #9 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(480):
     PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Function_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure),
     Object(PHPStan\Analyser\StatementContext))
     #10 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(371):
     PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Function_), Object(PHPStan\Analyser\MutatingScope), Object(Closure),
     Object(PHPStan\Analyser\StatementContext))
     #11 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(667):
     PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\If_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure),
     Object(PHPStan\Analyser\StatementContext))
     #12 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(371):
     PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\If_), Object(PHPStan\Analyser\MutatingScope), Object(Closure),
     Object(PHPStan\Analyser\StatementContext))
     #13 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(542):
     PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure),
     Object(PHPStan\Analyser\StatementContext))
     #14 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(371):
     PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope),
     Object(PHPStan\Node\ClassStatementsGatherer), Object(PHPStan\Analyser\StatementContext))
     #15 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(620):
     PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope),
     Object(PHPStan\Node\ClassStatementsGatherer), Object(PHPStan\Analyser\StatementContext))
     #16 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(340):
     PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure),
     Object(PHPStan\Analyser\StatementContext))
     #17 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(173): PHPStan\Analyser\NodeScopeResolver->processNodes(Array,
     Object(PHPStan\Analyser\MutatingScope), Object(Closure))
     #18 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(130): PHPStan\Analyser\FileAnalyser->analyseFile('/app/drupal/web...',
     Array, Object(PHPStan\Rules\LazyRegistry), Object(PHPStan\Collectors\Registry), NULL)
     #19 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
     PHPStan\Command\WorkerCommand->PHPStan\Command\{closure}(Array)
     #20 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/vendor/clue/ndjson-react/src/Decoder.php(117):
     _PHPStan_a540e44a3\Evenement\EventEmitter->emit('data', Array)
     #21 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
     _PHPStan_a540e44a3\Clue\React\NDJson\Decoder->handleData(Array)
     #22 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/Util.php(62): _PHPStan_a540e44a3\Evenement\EventEmitter->emit('data', Array)
     #23 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):
     _PHPStan_a540e44a3\React\Stream\Util::_PHPStan_a540e44a3\React\Stream\{closure}('{"action":"anal...')
     #24 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/DuplexResourceStream.php(154):
     _PHPStan_a540e44a3\Evenement\EventEmitter->emit('data', Array)
     #25 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(201):
     _PHPStan_a540e44a3\React\Stream\DuplexResourceStream->handleData(Resource id #5685)
     #26 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(173):
     _PHPStan_a540e44a3\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
     #27 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(96): _PHPStan_a540e44a3\React\EventLoop\StreamSelectLoop->run()
     #28 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259):
     PHPStan\Command\WorkerCommand->execute(Object(_PHPStan_a540e44a3\Symfony\Component\Console\Input\ArgvInput),
     Object(_PHPStan_a540e44a3\Symfony\Component\Console\Output\ConsoleOutput))
     #29 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870):
     _PHPStan_a540e44a3\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_a540e44a3\Symfony\Component\Console\Input\ArgvInput),
     Object(_PHPStan_a540e44a3\Symfony\Component\Console\Output\ConsoleOutput))
     #30 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261):
     _PHPStan_a540e44a3\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\WorkerCommand),
     Object(_PHPStan_a540e44a3\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_a540e44a3\Symfony\Component\Console\Output\ConsoleOutput))
     #31 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157):
     _PHPStan_a540e44a3\Symfony\Component\Console\Application->doRun(Object(_PHPStan_a540e44a3\Symfony\Component\Console\Input\ArgvInput),
     Object(_PHPStan_a540e44a3\Symfony\Component\Console\Output\ConsoleOutput))
     #32 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(122): _PHPStan_a540e44a3\Symfony\Component\Console\Application->run()
     #33 phar:///app/drupal/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(123): _PHPStan_a540e44a3\{closure}()
     #34 /app/drupal/vendor/phpstan/phpstan/phpstan(8): require('phar:///app/dru...')
     #35 /app/drupal/vendor/bin/phpstan(119): include('/app/drupal/ven...')
     #36 {main}
     Child process error (exit code 1):
 -- -----------------------------------------------------------------------------------------------------------------------------------------------------------------



 [ERROR] Found 2 errors


Used memory: 153 MB
```

**Comment by mglaman** [comment]
Thanks for reporting! We need to remove that `instanceof` and let the "method does not exist" PHPStan rule to run as normal.
